spring.application.name=home-rental-app1

server.address=0.0.0.0
server.port=8080

spring.data.mongodb.database=HomeRental
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sanahomerenting@gmail.com
spring.mail.password=rspc ueaf ougz bzqa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true




# spring.data.mongodb.database=home1

# spring.data.mongodb.uri=mongodb+srv://sandemoatlas:123456789atlas@san.h61lr.mongodb.net/?retryWrites=true&w=majority&appName=san